name = "DeconflictionSystem"
uuid = "..."  # Generate with UUIDs.uuid4()
authors = ["Rainer Rodrigues rainerrodrigues16@gmail.com"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"